# Site settings
title: Arianne Wallace
email: ariannewallace@gmail.com
url: https:/ariw654.github.io/cybersecurity-portfolio
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Ethical Hacker"
meta_author: Wallace Arianne

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF8FAB #80B3FF
  primary-rgb: "255,143,171" #"128,179,255"
  secondary: FFB3C6 #FD6E8A
  secondary-dark: FB6FG2 #A2122F

# Footer settings
footer:
  copyright: Arianne Wallace
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/arianne-wallace-854b18210
  - title: github
    url: https://github.com/AriW654

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:ariannewallace@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Wilmington, Delaware

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
